---
- name: Load version-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution_major_version }}.yml"
        - default.yml
      paths: "{{ role_path }}/vars"

- name: Add OpenTofu repository
  ansible.builtin.yum_repository:
    name: opentofu
    description: OpenTofu
    baseurl: "{{ repos_opentofu_baseurl }}"
    gpgcheck: true
    gpgkey: "{{ repos_opentofu_gpgkey }}"
    enabled: true
