---
- name: Prepare
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install sudo, python3, and openssh
      ansible.builtin.raw: dnf install -y sudo python3 openssh
      changed_when: false
